name: exarl_summit
channels:
  - conda-forge
  - file:///sw/sources/open-ce/conda-channel-v1.4.0
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access/linux-ppc64le/
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access/
  - defaults
  - file:///sw/sources/open-ce/conda-channel-v1.1.3
  - file:///sw/sources/open-ce/conda-channel/
  - file:///sw/sources/ibm-wml-ce/conda-channel/
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=2.0=cuda_2
  - _tensorflow_select=2.0=cuda_2
  - abseil-cpp=20200923.3=h29c3540_0
  - absl-py=0.12.0=py37h6ffa863_0
  - aiohttp=3.7.4.post0=py37h140841e_2
  - arrow-cpp=3.0.0=py37h16b90d4_15_cuda11.0
  - arrow-cpp-proc=3.0.0=cuda
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py37h6ffa863_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - av=8.0.3=py37h4eda063_3
  - blas=1.0=openblas
  - blinker=1.4=py37h6ffa863_0
  - boost_mp11=1.76.0=h99772c1_2
  - boto=2.49.0=py37_0
  - boto3=1.18.21=pyhd3eb1b0_0
  - botocore=1.21.41=pyhd3eb1b0_1
  - bottleneck=1.3.2=py37heb32a55_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py37h140841e_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h140841e_0
  - ca-certificates=2021.10.8=h1084571_0
  - cached-property=1.5.2=py_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=he491a88_1
  - catalogue=2.0.4=py37h6ffa863_0
  - certifi=2021.10.8=py37h35e4cab_1
  - cffi=1.14.6=py37hf9d8e4b_0
  - chardet=4.0.0=py37h6ffa863_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - clang=10.0.1=default_hc9b7fb1_0
  - clang-tools=10.0.1=default_hc9b7fb1_0
  - clangdev=10.0.1=default_hc9b7fb1_0
  - clangxx=10.0.1=default_h77df600_0
  - click=7.1.2=pyhd3eb1b0_0
  - cloudpickle=1.6.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py37h140841e_2
  - cryptography=3.4.8=py37h7ed74fa_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - cudnn=8.1.1_11.0=hf655df6_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cymem=2.0.5=py37h29c3540_0
  - cython=0.29.24=py37h29c3540_0
  - cython-blis=0.7.4=py37h140841e_1
  - dataclasses=0.8=pyh6d0b6a4_7
  - decorator=5.1.0=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - dm-tree=0.1.5=py37h00c0e08_4
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - fire=0.4.0=pyhccecc47_0
  - fontconfig=2.13.1=ha0a49a9_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.4=h5ab3b9f_0
  - fsspec=0.8.7=pyhd3eb1b0_0
  - future=0.18.2=py37_1
  - gast=0.4.0=pyhd3eb1b0_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h1318424_0
  - glog=0.5.0=h29c3540_0
  - gmock=1.10.0=h15a1290_2
  - gmp=6.2.1=h29c3540_0
  - gnutls=3.6.15=hd39c10c_0
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-auth=1.23.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-cloud-core=1.6.0=pyhd3eb1b0_0
  - google-cloud-storage=1.40.0=pyhd3eb1b0_0
  - google-crc32c=1.1.2=py37h140841e_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - google-resumable-media=1.3.1=pyhd3eb1b0_1
  - googleapis-common-protos=1.52.0=py37h6ffa863_0
  - graphite2=1.3.14=h23475e2_0
  - grpc-cpp=1.36.4=h0cec4b6_pb3.14_3
  - grpcio=1.35.0=py37hedb86c2_1
  - gtest=1.10.0=h15a1290_2
  - h5py=3.2.1=py37hf727584_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.6=hb1b8bf9_0
  - horovod=0.22.1=cuda11.0_system_py37_1
  - huggingface_hub=0.0.16=pyhc556d71_1
  - icu=58.2=he6710b0_3
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py37h6ffa863_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - jansson=2.13.1=h3275034_0
  - jasper=2.0.14=h07fcdf6_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h140841e_0
  - keras=2.6.0=pyhddf08d5_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.2=py37h29c3540_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h2045e0b_0
  - ld_impl_linux-ppc64le=2.33.1=h0f24833_7
  - leveldb=1.20=hf484d3e_1
  - libclang=10.0.1=default_hc9b7fb1_0
  - libclang-cpp=10.0.1=default_hc9b7fb1_0
  - libclang-cpp10=10.0.1=default_hc9b7fb1_0
  - libcrc32c=1.1.1=he6710b0_2
  - libdate=3.0.1=h99772c1_3
  - libevent=2.1.11=hafc74fa_3
  - libffi=3.3=he6710b0_2
  - libgcc-ng=8.2.0=h822a55f_1
  - libgfortran-ng=7.3.0=h822a55f_1
  - libglu=9.0.0=hf484d3e_1
  - libidn2=2.3.2=h140841e_0
  - liblightgbm=3.2.1=hf16effb_3_cuda11.0_system
  - libllvm10=10.0.1=h9b6764f_5
  - libllvm11=11.1.0=h621ed2f_0
  - libopenblas=0.3.13=h989ec91_0
  - libopencv=3.4.14=hf70ba83_py37_pb3.14_3
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h5f94dde_0
  - libstdcxx-ng=8.2.0=h822a55f_1
  - libtasn1=4.16.0=h140841e_0
  - libtensorflow=2.6.0=h4328f3b_cuda11.0_py37_pb3.14_1
  - libthrift=0.15.0=heb2aae8_0
  - libtiff=4.2.0=h781710b_0
  - libunistring=0.9.10=h140841e_0
  - libutf8proc=2.6.1=h140841e_0
  - libuuid=1.0.3=h140841e_2
  - libvpx=1.7.0=hf484d3e_0
  - libwebp=1.2.0=he32dc1f_0
  - libwebp-base=1.2.0=h140841e_0
  - libxcb=1.14=h7b6447c_0
  - libxgboost=1.4.2=cuda11.0_4
  - libxml2=2.9.12=hcd9f32a_0
  - lightgbm=3.2.1=py37hbf25c51_3_cuda11.0_system
  - lightgbm-proc=3.2.1=cuda
  - llvm-tools=10.0.1=h66086b3_5
  - llvmdev=10.0.1=h66086b3_5
  - llvmlite=0.37.0=py37h29c3540_1
  - lmdb=0.9.29=h29c3540_0
  - lz4-c=1.9.3=h29c3540_1
  - magma=2.5.4=cuda11.0_6
  - markdown=3.3.3=py37h6ffa863_0
  - markupsafe=2.0.1=py37h140841e_0
  - matplotlib=3.4.3=py37h6ffa863_0
  - matplotlib-base=3.4.3=py37he087750_0
  - more-itertools=8.8.0=pyhd3eb1b0_0
  - multidict=5.1.0=py37h140841e_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - murmurhash=1.0.5=py37h29c3540_0
  - nccl=2.8.3=cuda11.0_3
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hdc176a3_1
  - networkx=2.6.2=pyhd3eb1b0_0
  - nlohmann_json=3.9.1=h8ec9abc_3
  - nomkl=3.0=0
  - numactl=2.0.12=h459fe5f_5
  - numba=0.54.1=py37haab0e66_0
  - numexpr=2.7.3=py37h546262a_1
  - numpy=1.19.2=py37h6163131_0
  - numpy-base=1.19.2=py37h75fe3a5_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=py37_0
  - onnx=1.7.0=h27538de_py37_pb3.14_4
  - onnxconverter-common=1.8.1=py_pb3.14_1
  - onnxmltools=1.9.1=py_pb3.14_1
  - onnxruntime=1.7.2=ha2a263d_cuda11.0_py37_pb3.14_2
  - openblas=0.3.13=h6ffa863_0
  - openblas-devel=0.3.13=h6ffa863_0
  - opencv=3.4.14=py37_pb3.14_3
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1m=h140841e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optional-lite=3.4.0=h99772c1_2
  - orc=1.6.5=hb77ef19_2
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.3=py37h724cb3c_0
  - pathy=0.5.2=pyhd3eb1b0_0
  - pcre=8.45=h29c3540_0
  - pillow=8.3.1=py37h3f95422_0
  - pip=21.2.2=py37h6ffa863_0
  - pixman=0.40.0=h140841e_1
  - pluggy=0.13.1=py37h6ffa863_0
  - portpicker=1.3.1=py37h6ffa863_0
  - preshed=3.0.5=py37h29c3540_4
  - promise=2.3=py37h6ffa863_0
  - protobuf=3.14.0=py37h29c3540_1
  - psutil=5.8.0=py37h140841e_1
  - py=1.10.0=pyhd3eb1b0_0
  - py-opencv=3.4.14=hfeb2f93_py37_pb3.14_3
  - pyarrow=3.0.0=py37hfa44ca5_15_cuda11.0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pydantic=1.8.2=py37h140841e_0
  - pydeprecate=0.3.1=pyhccecc47_1
  - pyjwt=2.1.0=py37h6ffa863_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysocks=1.7.1=py37_1
  - pytest=5.4.3=py37h6ffa863_0
  - python=3.7.11=h836d2c2_0
  - python-clang=10.0.1=default_h1154ca9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.9.0=cuda11.0_py37_1
  - pytorch-base=1.9.0=h1234567_cuda11.0_py37_pb3.14_1
  - pytorch-lightning=1.4.4=py_1
  - pytorch-lightning-bolts=0.3.4=py_1
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py37h140841e_1
  - re2=2020.11.01=h29c3540_1
  - readline=8.1=h140841e_0
  - regex=2020.11.13=py37h140841e_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s3transfer=0.5.0=pyhd3eb1b0_0
  - sacremoses=0.0.45=py_1
  - safeint=3.0.26=h3da053b_3
  - scikit-learn=0.24.2=py37haab0e66_0
  - scipy=1.7.1=py37h45bdd02_2
  - sentencepiece=0.1.91=hd4d1946_py37_pb3.14_7
  - setuptools=50.3.2=py37h6ffa863_2
  - shellingham=1.3.1=pyhd3eb1b0_0
  - six=1.15.0=py37h6ffa863_0
  - skl2onnx=1.9.0=py_pb3.14_1
  - smart_open=3.0.0=py_0
  - snappy=1.1.8=he6710b0_0
  - spacy=3.1.2=py37h329fde5_1
  - spacy-legacy=3.0.8=py_1
  - sqlite=3.36.0=hd7247d8_0
  - srsly=2.4.1=py37h29c3540_0
  - tabulate=0.8.9=py37h6ffa863_0
  - tbb=2021.5.0=h66086b3_0
  - tensorboard=2.6.0=py_pb3.14_1
  - tensorboard-data-server=0.6.1=pyhb80c3c2_1
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.6.0=cuda11.0_py37_1
  - tensorflow-addons=0.14.0=py37he000102_2_cuda11.0
  - tensorflow-addons-proc=0.14.0=cuda
  - tensorflow-base=2.6.0=h1234567_cuda11.0_py37_pb3.14_1
  - tensorflow-datasets=4.4.0=h3ec5bd5_py37_pb3.14_1
  - tensorflow-estimator=2.6.0=py_1
  - tensorflow-hub=0.12.0=py_pb3.14_4
  - tensorflow-metadata=1.0.0=py_pb3.14_3
  - tensorflow-model-optimization=0.6.0=py37_1
  - tensorflow-probability=0.14.0=py37_1
  - tensorflow-text=2.6.0=h05bd93f_py37_pb3.14_1
  - termcolor=1.1.0=py37h6ffa863_1
  - tf2onnx=1.9.2=py37he902cde_1
  - thinc=8.0.8=py37h66e1fcb_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h7e00dab_0
  - tokenizers=0.10.3=py37h4ba5e45_1
  - torchmetrics=0.5.0=pyh078a8f9_1
  - torchtext=0.10.0=py37_1
  - torchvision=0.10.0=cuda11.0_py37_1
  - torchvision-base=0.10.0=cuda11.0_py37_1
  - tornado=6.1=py37h140841e_0
  - tqdm=4.62.2=pyhd3eb1b0_1
  - transformers=4.9.2=py_pb3.14_1
  - typeguard=2.12.0=py_0
  - typer=0.3.2=pyhd3eb1b0_0
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - uwsgi=2.0.19.1=py37h980472c_3
  - wasabi=0.8.2=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - wrapt=1.12.1=py37h7b6447c_1
  - x264=1!157.20191217=h7b6447c_0
  - xgboost=1.4.2=cuda11.0_py37_4
  - xgboost-ext=1.4.2=ha8d749a_4
  - xgboost-proc=1.4.2=cuda
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.5.1=py37h7b6447c_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=hc52992f_0
  - pip:
    - mpi4py==3.1.1
    - plotille==4.0.2
prefix: /ccs/home/vinayr/.conda/envs/exarl_summit
